### PR TITLE
Laur89/master

### PR DESCRIPTION
**Pull request by anthonyraymond**

### CODE REVIEW

**Comment by laur89** [comment]
lgtm

**Review by laur89 — COMMENTED** [review]
This rename slipped past my eyes - isn't `TooMany...` better, grammatically speaking?
@anthonyraymond

**Comment by anthonyraymond** [comment]
It sounds like indeed. I just renamed to get the filename and the class name the same, without thinking

**Comment by laur89** [comment]
Ah I had only renamed the file, not the class? Good catch. I'll push the rename to the 2nd PR.

**Pull request merged**
